const axios = require('axios');
const dotenv = require('dotenv');

dotenv.config({ path: '.env.dev' });

const data = {
    id: 36840028471615,
    token: '78a4ded396745a1936eeb94867d8646e',
    cart_token: 'c1-7743a01d14a69841e687352c38c7a0e0',
    email: 'harshasomisetty7@gmail.com',
    gateway: 'offsite_payment_method',
    buyer_accepts_marketing: false,
    buyer_accepts_sms_marketing: false,
    sms_marketing_phone: null,
    created_at: '2023-07-31T06:46:09+00:00',
    updated_at: '2023-07-31T02:46:58-04:00',
    landing_site: '/password',
    note: null,
    note_attributes: [],
    referring_site: 'https://solanatest8.myshopify.com/',
    shipping_lines: [
        {
            code: 'Economy',
            price: '0.00',
            original_shop_price: '0.00',
            original_shop_markup: '0.00',
            source: 'shopify',
            title: 'Economy',
            presentment_title: 'Economy',
            phone: null,
            tax_lines: [],
            custom_tax_lines: null,
            markup: '0.00',
            carrier_identifier: null,
            carrier_service_id: null,
            api_client_id: '580111',
            delivery_option_group: [Object],
            delivery_expectation_range: null,
            delivery_expectation_type: null,
            id: null,
            requested_fulfillment_service_id: null,
            delivery_category: null,
            validation_context: null,
            applied_discounts: [],
        },
    ],
    shipping_address: {
        first_name: 'Harsha',
        address1: '79 Huntington Street',
        phone: null,
        city: 'New Brunswick',
        zip: '08901',
        province: 'New Jersey',
        country: 'United States',
        last_name: 'Somisetty',
        address2: null,
        company: null,
        latitude: null,
        longitude: null,
        name: 'Harsha Somisetty',
        country_code: 'US',
        province_code: 'NJ',
    },
    taxes_included: false,
    total_weight: 57,
    currency: 'USD',
    completed_at: null,
    phone: null,
    customer_locale: 'en-US',
    line_items: [
        {
            key: '45820125348159',
            fulfillment_service: 'manual',
            gift_card: false,
            grams: 57,
            presentment_title: 'Selling Plans Ski Wax',
            presentment_variant_title: 'Selling Plans Ski Wax',
            product_id: 1,
            quantity: 1,
            requires_shipping: true,
            sku: '',
            tax_lines: [],
            taxable: true,
            title: 'Selling Plans Ski Wax',
            variant_id: 45820125348159,
            variant_title: 'Selling Plans Ski Wax',
            variant_price: '24.95',
            vendor: 'solanatest8',
            unit_price_measurement: [Object],
            compare_at_price: null,
            line_price: '24.95',
            price: '24.95',
            applied_discounts: [],
            destination_location_id: null,
            user_id: null,
            rank: null,
            origin_location_id: null,
            properties: null,
        },
        {
            key: '45820125053247',
            fulfillment_service: 'manual',
            gift_card: false,
            grams: 0,
            presentment_title: 'The Multi-location Snowboard',
            presentment_variant_title: '',
            product_id: 2,
            quantity: 1,
            requires_shipping: true,
            sku: '',
            tax_lines: [],
            taxable: true,
            title: 'The Multi-location Snowboard',
            variant_id: 45820125053247,
            variant_title: '',
            variant_price: '729.95',
            vendor: 'solanatest8',
            unit_price_measurement: [Object],
            compare_at_price: null,
            line_price: '729.95',
            price: '729.95',
            applied_discounts: [],
            destination_location_id: null,
            user_id: null,
            rank: null,
            origin_location_id: null,
            properties: null,
        },
    ],
    name: '#36840028471615',
    abandoned_checkout_url:
        'https://solanatest8.myshopify.com/79837528383/checkouts/ac/c1-7743a01d14a69841e687352c38c7a0e0/recover?key=afeb85e67255b7cee1c1312e063cc2f7',
    discount_codes: [],
    tax_lines: [],
    presentment_currency: 'USD',
    source_name: 'web',
    total_line_items_price: '754.90',
    total_tax: '0.00',
    total_discounts: '0.00',
    subtotal_price: '754.90',
    total_price: '754.90',
    total_duties: '0.00',
    device_id: null,
    user_id: null,
    location_id: null,
    source_identifier: null,
    source_url: null,
    source: null,
    closed_at: null,
    billing_address: {
        first_name: 'Harsha',
        address1: '79 Huntington Street',
        phone: null,
        city: 'New Brunswick',
        zip: '08901',
        province: 'New Jersey',
        country: 'United States',
        last_name: 'Somisetty',
        address2: null,
        company: null,
        latitude: null,
        longitude: null,
        name: 'Harsha Somisetty',
        country_code: 'US',
        province_code: 'NJ',
    },
    customer: {
        id: 7147919343935,
        email: 'harshasomisetty7@gmail.com',
        accepts_marketing: false,
        created_at: null,
        updated_at: null,
        first_name: 'Harsha',
        last_name: 'Somisetty',
        orders_count: 0,
        state: 'disabled',
        total_spent: '0.00',
        last_order_id: null,
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: null,
        tags: '',
        currency: 'USD',
        accepts_marketing_updated_at: null,
        admin_graphql_api_id: 'gid://shopify/Customer/7147919343935',
        default_address: {
            id: null,
            customer_id: 7147919343935,
            first_name: 'Harsha',
            last_name: 'Somisetty',
            company: null,
            address1: '79 Huntington Street',
            address2: null,
            city: 'New Brunswick',
            province: 'New Jersey',
            country: 'United States',
            zip: '08901',
            phone: null,
            name: 'Harsha Somisetty',
            province_code: 'NJ',
            country_code: 'US',
            country_name: 'United States',
            default: true,
        },
        last_order_name: null,
        marketing_opt_in_level: null,
    },
};

const headers = {
    'x-shopify-topic': 'checkouts/create',
    'x-shopify-hmac-sha256': 'hmac',
    'x-shopify-shop-domain': 'localhost:3001',
    'x-shopify-api-version': '2023-07',
    'x-shopify-webhook-id': 'e7891f97-fb5e-4d2f-a79e-3f1ab3769db6',
    'x-shopify-triggered-at': '2023-07-31T06:46:58.670068748Z',
};
axios
    .post(process.env.BACKEND_URL + '/checkouts', data, { headers })
    .then(response => {
        console.log(response.data);
    })
    .catch(error => {
        console.error(error);
    });
